services:
  postgres:
    image: postgres:16
    container_name: zbx-postgres
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=zabbix
    volumes:
      - ${PATH_VOLUME_POSTGRES}:/var/lib/postgresql/data
    networks:
      - zabbix-net
    restart: unless-stopped

  zbx-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zbx-server
    environment:
      - DB_SERVER_HOST=zbx-postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "10051:10051"
    depends_on:
      - postgres
    networks:
      - zabbix-net
    restart: unless-stopped

  zbx-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zbx-web
    environment:
      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
      - DB_SERVER_HOST=${DB_SERVER_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "8080:80"
    depends_on:
      - zbx-server
      - postgres
    networks:
      - zabbix-net
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "zabbix"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

  zbx-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zbx-agent
    environment:
      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
    networks:
      - zabbix-net
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local

networks:
  zabbix-net:
    driver: bridge